version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=DATABASE_URL
    depends_on:
      - db
    networks:
      - bio-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bio-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      - db
    networks:
      - bio-network

volumes:
  postgres_data:

networks:
  bio-network:
